name: NorthGate
favicon: null
layout_spectrum: 0.50022
typography_spectrum: 0.76594
title: Northgate Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40546c'
    - '#c5c5c9'
    - '#f4f4f1'
    - '#002842'
    - '#888e9c'
  brandStrength: 0.507861191406846
  lightness: 0.30880878679454327
  saturation: 0.9787343775387853
  rhythmicContrast: 0.4056516606360674
purpose: []
