name: NorthGate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7694236091338098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.507861191406846
  lightness: 0.30880878679454327
  saturation: 0.9787343775387853
  rhythmicContrast: 0.4056516606360674
purpose: []
